sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jasenpan1987/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jasenpan1987/docker-react npm run test
